### ISSUE TITLE
While calling methods from Reflection package, there is no response or exception

### ISSUE THREAD

**Issue by researchpoe** [frida/frida#111]
When I try to call a reflection method such as getClass().getMethods() inside my hook function of an android process such as onResume(), there is no output displayed also there is no exception message. 
However if I call getClass() method alone it works and prints the classname. When I call any method from the return value of getClass, the issue happens.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.

**Comment by c0n71nu3** [comment]
Am using Frida 10.0.15 and the above issue still seems to be present.

**Comment by c0n71nu3** [comment]
Actually, I was wrong. It needs to be done this way :
console.log("Result again : " + instance.class.getDeclaredFields()); 
instead of :
console.log("Result again : " + instance.getClass().getDeclaredFields()); 
and it works
