### ISSUE TITLE
frida immediately crashes any webkit process it attaches

### ISSUE THREAD

**Issue by bnovc** [frida/frida#194]
1. Open a Safari tab
2. `frida <pid>`

The WebContent now crashes.

**Comment by oleavr** [comment]
Thanks! Confirmed fixed in Frida 8.2.5.

**Comment by Azarattum** [comment]
It looks like the issue is still here...

iPhone 8, iOS 13.6.1, checkra1n
Frida v15.0.6

![image](https://user-images.githubusercontent.com/43073346/125614454-618a35f1-0b48-4ad0-8f63-1682f483510a.png)
![image](https://user-images.githubusercontent.com/43073346/125614586-cf99150b-e304-4d93-b5c2-9d182fb9c024.png)

**Comment by hoanghai27** [comment]
> It looks like the issue is still here...
> 
> iPhone 8, iOS 13.6.1, checkra1n
> Frida v15.0.6
> 
> ![image](https://user-images.githubusercontent.com/43073346/125614454-618a35f1-0b48-4ad0-8f63-1682f483510a.png)
> ![image](https://user-images.githubusercontent.com/43073346/125614586-cf99150b-e304-4d93-b5c2-9d182fb9c024.png)

Same on iPad, 14.7, checkra1n
Frida 15.0.8

**Comment by oleavr** [comment]
This used to work on older versions of iOS, but the sandbox profile has gotten stricter. I checked this recently, and then the issue was that we're using `poll()`, and that syscall isn't permitted. So we'd have to figure out how to issue a sandbox extension token for it – which I'm not sure is even possible.
