### ISSUE TITLE
iOS Spawn Issue - "Failed to attach: the connection is closed"

### ISSUE THREAD

**Issue by lorenzodifuccia** [frida/frida#2391]
**Device**: iPhone 8 - iOS 15.3.1 (19D52)
**Jailbreak**: palera1n - 1.4.1-main-6e4c7d6
**Frida**: 16.0.8

```bash
$ frida -U -f ws.hbang.Terminal
     ____
    / _  |   Frida 16.0.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to iPhone (id=XXX)

Failed to attach: the connection is closed
```

Instead, if I attach Frida on a running process, no issue is detected.

**Comment by lorenzodifuccia** [comment]
@oleavr, is there a way I can help you to gather more information about the issue? Provide some log? Debug something?

**Comment by lorenzodifuccia** [comment]
From CrashReporter:
```text
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000038
Exception Codes: 0x0000000000000001, 0x0000000000000038
VM Region Info: 0x38 is not in any region.  Bytes before following region: 4297572296
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   10027c000-100838000 [ 5872K] r-x/r-x SM=COW  .../frida-server
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  8

...

Thread 8 name:   Dispatch queue: re.frida.helper.queue
Thread 8 Crashed:
0   frida-server                  	       0x10036ec88 0x10027c000 + 994440
1   frida-server                  	       0x10036ee9c 0x10027c000 + 994972
2   frida-server                  	       0x10036ee9c 0x10027c000 + 994972
3   frida-server                  	       0x1002b4bb4 0x10027c000 + 232372
4   libdispatch.dylib             	       0x18199b1a8 _dispatch_client_callout + 16
5   libdispatch.dylib             	       0x181972724 _dispatch_continuation_pop$VARIANT$armv81 + 436
6   libdispatch.dylib             	       0x181983cf4 _dispatch_source_invoke$VARIANT$armv81 + 1320
7   libdispatch.dylib             	       0x181976024 _dispatch_lane_serial_drain$VARIANT$armv81 + 308
8   libdispatch.dylib             	       0x181976c04 _dispatch_lane_invoke$VARIANT$armv81 + 388
9   libdispatch.dylib             	       0x1819805dc _dispatch_workloop_worker_thread + 616
10  libsystem_pthread.dylib       	       0x1dc313e84 _pthread_wqthread + 284
11  libsystem_pthread.dylib       	       0x1dc3139f0 start_wqthread + 8

```

**Comment by AlecHaring** [comment]
I am experiencing the same issue.
```
Hardware Model:      iPhone8,1
Process:             frida-server [3681]
Path:                /usr/sbin/frida-server
Identifier:          frida-server
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           re.frida.server [703]

Date/Time:           2023-01-26 16:55:34.2393 -0500
Launch Time:         2023-01-26 16:55:31.9330 -0500
OS Version:          iPhone OS 15.7.2 (19H218)
Release Type:        User
Baseband Version:    9.61.00
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000038
Exception Codes: 0x0000000000000001, 0x0000000000000038
VM Region Info: 0x38 is not in any region.  Bytes before following region: 4297719752
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   1002a0000-10085c000 [ 5872K] r-x/r-x SM=COW  .../frida-server
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  7
```

```
Thread 7 name:   Dispatch queue: re.frida.helper.queue
Thread 7 Crashed:
0   frida-server                  	       0x100392c88 0x1002a0000 + 994440
1   frida-server                  	       0x100392e9c 0x1002a0000 + 994972
2   frida-server                  	       0x100392e9c 0x1002a0000 + 994972
3   frida-server                  	       0x1002d8bb4 0x1002a0000 + 232372
4   libdispatch.dylib             	       0x181180094 _dispatch_client_callout + 16
5   libdispatch.dylib             	       0x181122bb8 _dispatch_continuation_pop$VARIANT$mp + 440
6   libdispatch.dylib             	       0x1811348dc _dispatch_source_invoke$VARIANT$mp + 1668
7   libdispatch.dylib             	       0x181126610 _dispatch_lane_serial_drain$VARIANT$mp + 344
8   libdispatch.dylib             	       0x1811271f4 _dispatch_lane_invoke$VARIANT$mp + 408
9   libdispatch.dylib             	       0x181130ec8 _dispatch_workloop_worker_thread + 632
10  libsystem_pthread.dylib       	       0x1dc8cce10 _pthread_wqthread + 284
11  libsystem_pthread.dylib       	       0x1dc8cc93c start_wqthread + 8
```

```
Thread 7 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000010782c5cc   x2: 0x000000016ff2e16c   x3: 0x000000016ff2e278
    x4: 0xffffffffffffeb58   x5: 0x0000000000000020   x6: 0x0000000000000000   x7: 0x00000001bbd92bb0
    x8: 0x0000000000000004   x9: 0x0000000000000000  x10: 0x0000000000000001  x11: 0x00000001befca7ac
   x12: 0x00000001befca7ac  x13: 0x000000016db96170  x14: 0x000000010782c5cc  x15: 0x0000000060000000
   x16: 0xffffffffffffffe1  x17: 0x0060000000000000  x18: 0x0000000000000000  x19: 0x000000010782c5cc
   x20: 0x0000000000000000  x21: 0x000000016ff2e16c  x22: 0x0000000000000000  x23: 0x000000010782c5cc
   x24: 0x0000000000000000  x25: 0x000000016ff2f0e0  x26: 0x000000010207b9c8  x27: 0x0000000000000002
   x28: 0x000000016ff2f180   fp: 0x000000016ff2e150   lr: 0x0000000100392e9c
    sp: 0x000000016ff2e110   pc: 0x0000000100392c88 cpsr: 0x20000000
   far: 0x0000000000000038  esr: 0x92000006 (Data Abort) byte read Translation fault
```

**Comment by dLay-iOS** [comment]
same issue

**Comment by Numenorean** [comment]
resolved after resinstalling cydia substrate

**Comment by dLay-iOS** [comment]
resolved after uninstalling sileo substrate safe

**Comment by lorenzodifuccia** [comment]
> resolved after resinstalling cydia substrate  

@Numenorean How did you reinstall Substrate?
Trying to re-jailbreak didn't solve the problem for me, also deleting the Safe Mode... 🤷🏻‍♂️

**Comment by Numenorean** [comment]
@lorenzodifuccia for me it was searching for Cydia Substrate and reinstalling it with Modify button. You may have other replacement. Also take into account that i have installed Substrate Safe Mode

**Comment by lorenzodifuccia** [comment]
@Numenorean, which Jailbreak and OS are you using?

**Comment by Numenorean** [comment]
@lorenzodifuccia iPhoneSE 2016 14.4 with checkra1n
