### ISSUE TITLE
Issue attaching to iPhone 15 Simulator processes 

### ISSUE THREAD

**Issue by comed-ian** [frida/frida#2763]
Frida attached successfully to the target process developed in Xcode 14 and running on the iPhone 14 simulator. Upgrading MacOS yesterday to Sonoma 14.3 requires an upgrade to Xcode 15, thereby requiring an additional upgrade to iPhone 15 simulators. Attempting to attach to the identical process (with no changes to source code), results in the following error:

```
❯❯  pip list
Package           Version
----------------- --------
...
frida             16.1.11
frida-tools       12.3.0

❯❯  frida -p 29032                        
     ____
    / _  |   Frida 16.1.11 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Failed to attach: module not found at "/usr/lib/libSystem.B.dylib"  
```

Analysis in Xcode shows that the libSystem.B.dylib library is present at `/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib`

**Comment by comed-ian** [comment]
As a further data point, installing Xcode 14 and modifying the Info.plist file to allow execution permits running an iPhone 14 simulator on the latest Sonoma 14.3. This is the same environment that was working yesterday prior to upgrading MacOS. Frida exits with the same error, and per Xcode the path to libSystem.B.dylib is `/Users/<username>/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libSystem.B.dylib`. Note that in this case I am running Xcode 14.3 directly from my `Downloads` directory. 

It would appear that the root cause is therefore a result of the MacOS upgrade. 

```
Attaching to PID 33598
     ____
    / _  |   Frida 16.1.11 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Failed to attach: module not found at "/usr/lib/libSystem.B.dylib" 
```

**Comment by pimterry** [comment]
I've also been running into this and I haven't found a clean solution yet, looks like Frida is currently unusable on the latest Mac iOS simulators.

**Comment by ChiChou** [comment]
Sometimes this happens to jailbroken iPhone too

**Comment by noises1990** [comment]
This is also occurring on my side, are there no updates regarding this issue?

I've found another post on the apple developer forums:
- https://forums.developer.apple.com/forums/thread/748274

**Comment by bensh** [comment]
Also getting this using frida ipa dump or bagbak.
iPhone X - 15.6
```
iPhoneX:/usr/lib root# frida-server --version
16.1.4
```
```
FATAL ERROR
[Error: Module not found at "/usr/lib/libSystem.B.dylib"]
Start the target app com.sabeeapp.guestadvisor
module not found at "/usr/lib/libSystem.B.dylib"
```

**Comment by ChiChou** [comment]
@bensh use iPhone X with iOS 16, works well there

**Comment by ChiChou** [comment]
@mrmacete Seems like the patch is simple. 

https://github.com/frida/frida-gum/blob/452a1b8f3569497b94e4407dbb0672c36f986d30/gum/backend-darwin/gumdarwinmoduleresolver.c#L392

There is an assumption that dyld_sim's index is 0, but somehow it is not true one latest simulator

@bensh 

For the jailbroken iOS, I have no environment to debug yet

**Comment by ChiChou** [comment]
@noises1990 @comed-ian This issue should be resolved now

**Comment by andermoran** [comment]
@ChiChou is iOS sim supposed to be working now? I still get 

`Module not found at "/usr/lib/libSystem.B.dylib"`

on sim running iOS 18 when trying to attach to simulator apps

**Comment by nccensus** [comment]
Same issue for macOS 15.5, Xcode 16.4:
`Module not found at "/usr/lib/libSystem.B.dylib"`

**Comment by gemesa** [comment]
Does anyone have any kind of solution for this? Dirty or clean.

**Comment by ChiChou** [comment]
@gemesa This has been already merged upstream, but not published to the package yet 
https://github.com/frida/frida-gum/pull/1031

**Comment by gemesa** [comment]
I just built frida from source and it is indeed working. Thanks for fixing it.
