### ISSUE TITLE
Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject

### ISSUE THREAD

**Issue by AndreSkjelbred** [frida/frida#2867]
Running frida 16.2.3 on google pixel 8a. When running the command: adb shell su -c /data/local/tmp/frida-server & I keep getting this error.

![image](https://github.com/frida/frida/assets/100943300/35a8bbce-e49e-4115-87c4-928a29039bc7)

**Comment by AndreSkjelbred** [comment]
frida-ps -Uai
Failed to enumerate applications: java API only partially available; please file a bug. Missing: _ZNK3art6Thread13DecodeJObjectEP8_jobject

**Comment by AndreSkjelbred** [comment]
Tried with 16.2.5 aswell and same error

**Comment by AndreSkjelbred** [comment]
Still the same with 16.3.1

**Comment by jpstotz** [comment]
Seems to be the same problem as in #2468 so latest frida-server should fix it.

**Comment by 5andr0** [comment]
It shouldn't fail with 16.3.1. Works for me on Pixel 7a Android 14. Did you guys also update the frida-server version?

**Comment by gaganshetty645hk** [comment]
Hi All, i had tried this with Pixel 8 with android 14, still facing this issue what is that solution for this?, i had tried from latest version till 16.2.18 that worked but not as expected, didn't hook into any process.
/frida-server-16.3.1-android-arm64                                            <
{"type":"error","description":"Error: Unable to perform state transition; please file a bug","stack":"Error: Unable to perform state transition; please file a bug\n    at bt (frida/node_modules/frida-java-bridge/lib/android.js:577:1)\n    at frida/node_modules/frida-java-bridge/lib/class-model.js:112:1\n    at Function.build (frida/node_modules/frida-java-bridge/lib/class-model.js:7:1)\n    at k._make (frida/node_modules/frida-java-bridge/lib/class-factory.js:168:1)\n    at k.use (frida/node_modules/frida-java-bridge/lib/class-factory.js:62:1)\n    at frida/node_modules/frida-java-bridge/index.js:224:1\n    at c.perform (frida/node_modules/frida-java-bridge/lib/vm.js:12:1)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:223:1)\n    at _.perform (frida/node_modules/frida-java-bridge/index.js:204:1)\n    at /internal-agent.js:490:6","fileName":"frida/node_modules/frida-java-bridge/lib/android.js","lineNumber":577,"columnNumber":1}

**Comment by oOooOOooOOOoc** [comment]
> It shouldn't fail with 16.3.1. Works for me on Pixel 7a Android 14. Did you guys also update the frida-server version?

Thanks a lot!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Works for me!!!!!!!!!!!!!!!!!! (Android 14 either) Greatly thanks for saving me from the loop "try new version and fail"!!!!!!!!!!!!!!!!!!!!!!!!!!!
