### ISSUE TITLE
Starting from frida_16.7.0, frida failed to start on iPad

### ISSUE THREAD

**Issue by liugang** [frida/frida#3457]
Starting from frida_16.7.0, frida failed to start on iPad;

```
-rw-r--r--  1 root wheel 16620480 May 17 14:48 frida_16.6.1_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16631336 May 17 14:56 frida_16.6.6_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16800204 May 17 14:55 frida_16.7.0_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16848464 May 17 14:54 frida_16.7.12_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16847924 May 17 14:53 frida_16.7.17_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16846528 May 17 14:51 frida_16.7.18_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16845908 May 17 14:49 frida_16.7.19_iphoneos-arm.deb
```

I have tried the 16.6 series and have been able to run it successfully;
But all versions of the 16.7 series are failures:

```
-rw-r--r--  1 root wheel 16620480 May 17 14:48 frida_16.6.1_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16631336 May 17 14:56 frida_16.6.6_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16800204 May 17 14:55 frida_16.7.0_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16848464 May 17 14:54 frida_16.7.12_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16847924 May 17 14:53 frida_16.7.17_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16846528 May 17 14:51 frida_16.7.18_iphoneos-arm.deb
-rw-r--r--  1 root wheel 16845908 May 17 14:49 frida_16.7.19_iphoneos-arm.deb
(failed reverse-i-search)`install': rm /usr/sb^C/frida-server
iPad:~ root# dpkg -i frida_16.7.19_iphoneos-arm.deb
(Reading database ... 4345 files and directories currently installed.)
Preparing to unpack frida_16.7.19_iphoneos-arm.deb ...
Unpacking re.frida.server (16.7.19) over (16.6.6) ...
Setting up re.frida.server (16.7.19) ...
iPad:~ root# ps aux |grep frida
root            9452   0.0  0.3 407926496   6064 s001  S+    3:09PM   0:00.01 grep frida
iPad:~ root# frida-server 
Segmentation fault: 11
iPad:~ root# dpkg -i frida_16.6.6_iphoneos-arm.deb
dpkg: warning: downgrading re.frida.server from 16.7.19 to 16.6.6
(Reading database ... 4345 files and directories currently installed.)
Preparing to unpack frida_16.6.6_iphoneos-arm.deb ...
Unpacking re.frida.server (16.6.6) over (16.7.19) ...
Setting up re.frida.server (16.6.6) ...
iPad:~ root# ps aux |grep frida
root            9480   2.7  0.3 407926352   5968 s001  R+    3:09PM   0:00.02 grep frida
root            9475   0.0  0.4 407937632   8992   ??  Ss    3:09PM   0:00.02 /usr/sbin/frida-server
iPad:~ root# 
```

![Image](https://github.com/user-attachments/assets/9500eeba-e0f1-4533-85f4-bf61d09ca5f8)

device detail:
```
- iPad
- iPad 6 128GB Space Gray
- Charging +100
- Firmware version: 14.2 (18B92)
- Activated: Installed AFC2
- Activated: iPad7,5 (A1893) MR7J2 CH/A
- Serial number: DMQ______JF8M
- ECID: 00056______E0A6
- Baseband: 30B8
- Device ID (UUID): 34EAC6028
- Apple ID: iCloud
- Production date: April 1, 2018 (Week 13)
- Storage type: Sales region
- CPU: A10 Quad-core CPU details
- TLC hard drive details: 294 times
- Battery details: 91% battery details
```

![Image](https://github.com/user-attachments/assets/fdd9a474-2db6-4fad-9ef4-e382eae21d2d)

frida_16.7.19_iphoneos-arm.deb  crash log:

```
iPad:/var/mobile/Library/Logs/CrashReporter root# cat frida-server-2025-05-17-205359.ips
{"app_name":"frida-server","timestamp":"2025-05-17 20:53:59.00 +0800","app_version":"","slice_uuid":"787a2987-e944-3538-b446-b4b4a8567562","build_version":"","platform":2,"share_with_app_devs":1,"is_first_party":1,"bug_type":"109","os_version":"iPhone OS 14.2 (18B92)","incident_id":"5A1936C2-7EA5-4C9D-9DA2-8881F0E26A16","name":"frida-server"}
Incident Identifier: 5A1936C2-7EA5-4C9D-9DA2-8881F0E26A16
CrashReporter Key:   fcfc2fc2bdb42a4e95625b16249bcd955f75c0cb
Hardware Model:      iPad7,5
Process:             frida-server [22441]
Path:                /usr/sbin/frida-server
Identifier:          frida-server
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           re.frida.server [25434]


Date/Time:           2025-05-17 20:53:58.9339 +0800
Launch Time:         2025-05-17 20:53:58.8597 +0800
OS Version:          iPhone OS 14.2 (18B92)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
VM Region Info: 0x10 is not in any region.  Bytes before following region: 4365320176
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   104318000-104994000 [ 6640K] r-x/r-x SM=COW  .../frida-server

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [22441]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_platform.dylib      	0x00000001d83aa724 0x1d83a3000 + 30500
1   frida-server                  	0x000000010445797c 0x104318000 + 1309052
2   frida-server                  	0x000000010437ae14 0x104318000 + 405012
3   frida-server                  	0x000000010437ac50 0x104318000 + 404560
4   frida-server                  	0x000000010437ab0c 0x104318000 + 404236
5   frida-server                  	0x0000000104374b04 0x104318000 + 379652
6   frida-server                  	0x0000000104374268 0x104318000 + 377448
7   frida-server                  	0x000000010431c36c 0x104318000 + 17260
8   libdyld.dylib                 	0x0000000192613588 0x192612000 + 5512

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000010   x1: 0x0000000000000010   x2: 0x000000016bae793c   x3: 0x0000000000000004
    x4: 0x000000010600c100   x5: 0x0000000000000000   x6: 0x0000000104b0d9d0   x7: 0x0000000000000000
    x8: 0x940826e81f2100f2   x9: 0x940826e81f2100f2  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000001  x13: 0x0000000000000002  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x00000001d83aa720  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000010
   x20: 0x000000016bae7b20  x21: 0x0000000000000010  x22: 0x000000010600c0a0  x23: 0x000000010580b880
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016bae7cd8   fp: 0x000000016bae7ae0   lr: 0x000000010445797c
    sp: 0x000000016bae7ad0   pc: 0x00000001d83aa724 cpsr: 0x60000000
   esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
0x104318000 - 0x104993fff frida-server arm64  <787a2987e9443538b446b4b4a8567562> /usr/sbin/frida-server
0x104a8c000 - 0x104a97fff libobjc-trampolines.dylib arm64  <b8c2db0f13bb343d93d8e8c6f6cee07e> /usr/lib/libobjc-trampolines.dylib
0x104aa0000 - 0x104ab7fff libsubstitute.dylib arm64  <0fbb851edb86325daa9a49f1a1722445> /usr/lib/libsubstitute.dylib
0x104ac8000 - 0x104acffff libsubstrate.dylib arm64  <52123f7ce68a36dc8d3f93dca9c4dad6> /usr/lib/libsubstrate.dylib
0x104cd4000 - 0x104d3ffff dyld arm64  <f756a8d55a803b4d996236fe0e7638c2> /usr/lib/dyld
0x104dc0000 - 0x1051affff substitute-inserter.dylib arm64  <9ee31a91880e3d089c9d10a394ff8b48> /usr/lib/substitute-inserter.dylib
0x105230000 - 0x1054effff substitute-loader.dylib arm64  <17f0fb61e3eb3a7cb2fe6e82d6769b0c> /usr/lib/substitute-loader.dylib
0x192593000 - 0x192611fff libdispatch.dylib arm64  <6c143c51288f3cd084dd17b9a0aaee62> /usr/lib/system/libdispatch.dylib
0x192612000 - 0x192648fff libdyld.dylib arm64  <e31c0887c99930479b80203248ec2396> /usr/lib/system/libdyld.dylib
0x192649000 - 0x1928a0fff libicucore.A.dylib arm64  <9fc7dac3deed3a479abbe36867045ba5> /usr/lib/libicucore.A.dylib
0x1928a1000 - 0x192c4afff CoreFoundation arm64  <96f8386dd88a3c89a323a17975c3317f> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x192e2e000 - 0x192ea6fff SystemConfiguration arm64  <75fec68015053f2e84dc4a0a8586c617> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x192f92000 - 0x193413fff CFNetwork arm64  <e261fa7130e23e6a8db232ecf79b30bf> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x193414000 - 0x193ad9fff libnetwork.dylib arm64  <c67a2d7144153f82939965c3956520ae> /usr/lib/libnetwork.dylib
0x193b4b000 - 0x193de5fff Foundation arm64  <f1bc26a1f5bb36f7a65ad5f232dbf902> /System/Library/Frameworks/Foundation.framework/Foundation
0x199932000 - 0x199a6ffff Security arm64  <149f8d12822a31a198bf48ce690f678d> /System/Library/Frameworks/Security.framework/Security
0x19b5ce000 - 0x19b5f3fff libsystem_info.dylib arm64  <3536d46d36cd3af4b92c67e4bdebd8c6> /usr/lib/system/libsystem_info.dylib
0x19b5f4000 - 0x19b670fff libsystem_c.dylib arm64  <edf3e843a62a3dd092ccebe94d5a83e3> /usr/lib/system/libsystem_c.dylib
0x19cf52000 - 0x19cff8fff IOKit arm64  <c50846c1e80d37e886984cf410de47a6> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x1a0efd000 - 0x1a0f5afff libMobileGestalt.dylib arm64  <448540b0eca03930b98b2d18101114d6> /usr/lib/libMobileGestalt.dylib
0x1a13ca000 - 0x1a13ecfff libsystem_malloc.dylib arm64  <9f2d3d4683d9358f972c1cf61c073a31> /usr/lib/system/libsystem_malloc.dylib
0x1a3357000 - 0x1a3366fff libsystem_networkextension.dylib arm64  <0e55773557ba3611994ce782f3cbfe75> /usr/lib/system/libsystem_networkextension.dylib
0x1a6366000 - 0x1a639bfff libobjc.A.dylib arm64  <7cad222912fa3d6c82005306fb157fa4> /usr/lib/libobjc.A.dylib
0x1a63fc000 - 0x1a6455fff libc++.1.dylib arm64  <88496d66c6683f1797c5d0c91e8bee42> /usr/lib/libc++.1.dylib
0x1a6456000 - 0x1a646efff libc++abi.dylib arm64  <464199d1cdfe3663bedfcbc1b5f19491> /usr/lib/libc++abi.dylib
0x1a65d9000 - 0x1a6619fff CoreAutoLayout arm64  <83a9b00eb095347aa9a2fd147deb1d75> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/CoreAutoLayout
0x1a7fb4000 - 0x1a7fcafff libsystem_trace.dylib arm64  <4ed5b6b480e9322784b590bc92570931> /usr/lib/system/libsystem_trace.dylib
0x1aaf4b000 - 0x1ab0cdfff libsqlite3.dylib arm64  <a814e2dc328e3acd860ff0e3ee3a180e> /usr/lib/libsqlite3.dylib
0x1abc61000 - 0x1abc6bfff libsystem_notify.dylib arm64  <4dbd2e3e6bc43d1388d0e01ba0cc4e07> /usr/lib/system/libsystem_notify.dylib
0x1abd16000 - 0x1abd85fff libcorecrypto.dylib arm64  <071f7a201cf6324783d7d4e309a64c16> /usr/lib/system/libcorecrypto.dylib
0x1abe79000 - 0x1abe8ffff libsystem_asl.dylib arm64  <441adb81097f31d6a85d380a72993d66> /usr/lib/system/libsystem_asl.dylib
0x1af5a5000 - 0x1af5affff IOMobileFramebuffer arm64  <674f742e890231f3b8999fac2c9eb8fa> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
0x1b20ae000 - 0x1b20bffff IOSurface arm64  <19dd2ad445e03197a5c453b357f361a0> /System/Library/Frameworks/IOSurface.framework/IOSurface
0x1b264e000 - 0x1b2655fff libsystem_symptoms.dylib arm64  <cf41ba3e1ea634e58692d79f7c1b90b8> /usr/lib/system/libsystem_symptoms.dylib
0x1bd336000 - 0x1bd366fff libsystem_kernel.dylib arm64  <8bcb6ff951623657a2e25ce5704353e6> /usr/lib/system/libsystem_kernel.dylib
0x1bfdac000 - 0x1bfdadfff libSystem.B.dylib arm64  <5f81896adca13ef7999f6c5da89a750b> /usr/lib/libSystem.B.dylib
0x1c01ee000 - 0x1c025cfff libarchive.2.dylib arm64  <cfb67f017e673b5294fabf9e2d00cc61> /usr/lib/libarchive.2.dylib
0x1d03d3000 - 0x1d03d3fff SoftLinking arm64  <2a4d987221d13057a2e4287595be79b5> /System/Library/PrivateFrameworks/SoftLinking.framework/SoftLinking
0x1d6c90000 - 0x1d6cc2fff libCRFSuite.dylib arm64  <a30268c7824a34c59182cf051f933a2c> /usr/lib/libCRFSuite.dylib
0x1d7376000 - 0x1d738cfff libapple_nghttp2.dylib arm64  <741cbe1e00f93a20b845d77885621920> /usr/lib/libapple_nghttp2.dylib
0x1d74ae000 - 0x1d74befff libbsm.0.dylib arm64  <62262c68bf203584b2ea3889b8647e16> /usr/lib/libbsm.0.dylib
0x1d74bf000 - 0x1d74cbfff libbz2.1.0.dylib arm64  <bdcdbdcc24953c7e90401c44963079e0> /usr/lib/libbz2.1.0.dylib
0x1d74cc000 - 0x1d74ccfff libcharset.1.dylib arm64  <72b0c36f725f38fea3579a515aaf64b9> /usr/lib/libcharset.1.dylib
0x1d74df000 - 0x1d74f6fff libcompression.dylib arm64  <36dd56ca87a33b8bbc2e9ee086e82284> /usr/lib/libcompression.dylib
0x1d74f7000 - 0x1d750cfff libcoretls.dylib arm64  <31987a4e4ec23c89952efad70a0d71d5> /usr/lib/libcoretls.dylib
0x1d750d000 - 0x1d750efff libcoretls_cfhelpers.dylib arm64  <56fa9fe8ebb83d17872877e4c5cd0848> /usr/lib/libcoretls_cfhelpers.dylib
0x1d7539000 - 0x1d7540fff libdns_services.dylib arm64  <8d3832488b4333b492251a634982e109> /usr/lib/libdns_services.dylib
0x1d755e000 - 0x1d755efff libenergytrace.dylib arm64  <ee2039679a7d332c8ac386c6ddd87e24> /usr/lib/libenergytrace.dylib
0x1d75ae000 - 0x1d769ffff libiconv.2.dylib arm64  <6bf1c6e1e4b93cc3928eaa07c4ecdfc5> /usr/lib/libiconv.2.dylib
0x1d76bd000 - 0x1d76befff liblangid.dylib arm64  <982686583ed13ebaa2cc14345035abe9> /usr/lib/liblangid.dylib
0x1d76cb000 - 0x1d76e3fff liblzma.5.dylib arm64  <60e6e4ad8b823583b81e7e39df26637f> /usr/lib/liblzma.5.dylib
0x1d7d57000 - 0x1d7d8afff libpcap.A.dylib arm64  <0d7a2422cdb838ce9604933d6ced3742> /usr/lib/libpcap.A.dylib
0x1d7e81000 - 0x1d7e98fff libresolv.9.dylib arm64  <d007e203385a3a9fad4c45aa4ebc975f> /usr/lib/libresolv.9.dylib
0x1d7ee7000 - 0x1d7fccfff libxml2.2.dylib arm64  <3102a95fbfd13d2292ed7d4f31ce994f> /usr/lib/libxml2.2.dylib
0x1d7ffa000 - 0x1d800bfff libz.1.dylib arm64  <d73106766fb234ab89d92a7d3e5a53e2> /usr/lib/libz.1.dylib
0x1d8238000 - 0x1d823dfff libcache.dylib arm64  <93f46de334c83b548e87b685e63149e7> /usr/lib/system/libcache.dylib
0x1d823e000 - 0x1d824afff libcommonCrypto.dylib arm64  <163c756fa4413bb7b2ca067463d98526> /usr/lib/system/libcommonCrypto.dylib
0x1d824b000 - 0x1d824ffff libcompiler_rt.dylib arm64  <6749df438089311b939a87f9ca479efd> /usr/lib/system/libcompiler_rt.dylib
0x1d8250000 - 0x1d8258fff libcopyfile.dylib arm64  <5ea5d77aebc930459a3ccf1838e73c6b> /usr/lib/system/libcopyfile.dylib
0x1d8336000 - 0x1d8336fff liblaunch.dylib arm64  <a0b8f064a9ee310e8b976e27f49a05f2> /usr/lib/system/liblaunch.dylib
0x1d8337000 - 0x1d833cfff libmacho.dylib arm64  <863174fc64663104aca38d1d4a82d075> /usr/lib/system/libmacho.dylib
0x1d833d000 - 0x1d833ffff libremovefile.dylib arm64  <fc34eec2b9013ebbbc31e73f38842b70> /usr/lib/system/libremovefile.dylib
0x1d8340000 - 0x1d8341fff libsystem_blocks.dylib arm64  <bc8afa7d401e35f789e89e7a59aef82b> /usr/lib/system/libsystem_blocks.dylib
0x1d8342000 - 0x1d8344fff libsystem_collections.dylib arm64  <828126f3e6583da2aceac728678588de> /usr/lib/system/libsystem_collections.dylib
0x1d8345000 - 0x1d8349fff libsystem_configuration.dylib arm64  <27db1d5d607530bf888edca2c13e80ef> /usr/lib/system/libsystem_configuration.dylib
0x1d834a000 - 0x1d835cfff libsystem_containermanager.dylib arm64  <cb5192ce591f3bb8bc455646bb298477> /usr/lib/system/libsystem_containermanager.dylib
0x1d835d000 - 0x1d835efff libsystem_coreservices.dylib arm64  <b3a52ad613a83868ab485b08b9c8fa23> /usr/lib/system/libsystem_coreservices.dylib
0x1d835f000 - 0x1d8368fff libsystem_darwin.dylib arm64  <e5bec594b4643527b60ef752cb6e3386> /usr/lib/system/libsystem_darwin.dylib
0x1d8369000 - 0x1d8371fff libsystem_dnssd.dylib arm64  <e4268fdd91b5313994546631865c32ca> /usr/lib/system/libsystem_dnssd.dylib
0x1d8372000 - 0x1d8374fff libsystem_featureflags.dylib arm64  <1e7cd17eb5283b85bf4a27e1aa8dfa3e> /usr/lib/system/libsystem_featureflags.dylib
0x1d8375000 - 0x1d83a2fff libsystem_m.dylib arm64  <dedeec341f9e3964a5ff79cddc6a811e> /usr/lib/system/libsystem_m.dylib
0x1d83a3000 - 0x1d83adfff libsystem_platform.dylib arm64  <abb790d318753996aaee06e7568ea1c9> /usr/lib/system/libsystem_platform.dylib
0x1d83ae000 - 0x1d83aefff libsystem_product_info_filter.dylib arm64  <61b5d8563fb33fe9b30540a45f659732> /usr/lib/system/libsystem_product_info_filter.dylib
0x1d83af000 - 0x1d83bffff libsystem_pthread.dylib arm64  <93c7f0dc89f13162a1196fc88028d027> /usr/lib/system/libsystem_pthread.dylib
0x1d83c0000 - 0x1d83c3fff libsystem_sandbox.dylib arm64  <176b1087aaad36258e7ffc497673706c> /usr/lib/system/libsystem_sandbox.dylib
0x1d83c4000 - 0x1d83cdfff libunwind.dylib arm64  <b7cd41ad513335ac84299bc0dcc6511b> /usr/lib/system/libunwind.dylib
0x1d83ce000 - 0x1d8400fff libxpc.dylib arm64  <e3552d23adfb36feb7d0b23090553c49> /usr/lib/system/libxpc.dylib

EOF
```

**Comment by oleavr** [comment]
Should be fixed in 16.7.1. Please reopen if not.

**Comment by oleavr** [comment]
Wait, sorry, I misread as 17.0.0. Reopening.

**Comment by liugang** [comment]
I downloaded the latest frida_17.0.1, but still can't start it.


```
iPad:~ root# dpkg -i frida_17.0.1_iphoneos-arm.deb
(Reading database ... 4345 files and directories currently installed.)
Preparing to unpack frida_17.0.1_iphoneos-arm.deb ...
Unpacking re.frida.server (17.0.1) over (16.6.6) ...
Setting up re.frida.server (17.0.1) ...
iPad:~ root# ps aux |grep frida
root           22800   0.0  0.3 407918160   5776 s000  R+    1:32AM   0:00.02 grep frida
```

```
iPad:~ root# frida-server
Segmentation fault: 11
```

```
iPad:~ root# cat /var/mobile/Library/Logs/CrashReporter/
Assistant/                                    frida-server-2025-05-19-013232.ips            frida-server-2025-05-19-013308.ips
Aweme.wakeups_resource-2025-05-18-203044.ips  frida-server-2025-05-19-013237.000.ips        frida-server-2025-05-19-013313.ips
DiagnosticLogs/                               frida-server-2025-05-19-013237.ips            frida-server-2025-05-19-013318.ips
Panics/                                       frida-server-2025-05-19-013242.ips            frida-server-2025-05-19-013323.ips
Retired/                                      frida-server-2025-05-19-013247.ips            log-sessions-2025-05-18-203010.session
com.apple.appstored/                          frida-server-2025-05-19-013252.ips            proactive_notification-2025-05-18-222949.ips
frida-server-2025-05-19-013222.ips            frida-server-2025-05-19-013258.ips            xp_amp_app_usage_dnu-2025-05-19-001602.ips
frida-server-2025-05-19-013227.ips            frida-server-2025-05-19-013303.ips
iPad:~ root# cat /var/mobile/Library/Logs/CrashReporter/frida-server-2025-05-19-013323.ips
{"app_name":"frida-server","timestamp":"2025-05-19 01:33:23.00 +0800","app_version":"","slice_uuid":"eed454bb-b67d-392d-90dc-9a4a58fed889","build_version":"","platform":2,"share_with_a
pp_devs":1,"is_first_party":1,"bug_type":"109","os_version":"iPhone OS 14.2 (18B92)","incident_id":"04A64FA5-4846-49C4-9820-CAFE6A93F3B8","name":"frida-server"}
Incident Identifier: 04A64FA5-4846-49C4-9820-CAFE6A93F3B8
CrashReporter Key:   fcfc2fc2bdb42a4e95625b16249bcd955f75c0cb
Hardware Model:      iPad7,5
Process:             frida-server [22812]
Path:                /usr/sbin/frida-server
Identifier:          frida-server
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           re.frida.server [25505]


Date/Time:           2025-05-19 01:33:23.3892 +0800
Launch Time:         2025-05-19 01:33:23.3163 +0800
OS Version:          iPhone OS 14.2 (18B92)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
VM Region Info: 0x20 is not in any region.  Bytes before following region: 4305305568
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->
      __TEXT                   1009dc000-10106c000 [ 6720K] r-x/r-x SM=COW  .../frida-server

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [22812]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_platform.dylib            0x00000001d83aa724 0x1d83a3000 + 30500
1   frida-server                        0x0000000100b1b97c 0x1009dc000 + 1309052
2   frida-server                        0x0000000100a3ee14 0x1009dc000 + 405012
3   frida-server                        0x0000000100a3ec50 0x1009dc000 + 404560
4   frida-server                        0x0000000100a3eb0c 0x1009dc000 + 404236
5   frida-server                        0x0000000100a38b04 0x1009dc000 + 379652
6   frida-server                        0x0000000100a38268 0x1009dc000 + 377448
7   frida-server                        0x00000001009e036c 0x1009dc000 + 17260
8   libdyld.dylib                       0x0000000192613588 0x192612000 + 5512

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000020   x1: 0x0000000000000020   x2: 0x000000016f42393c   x3: 0x0000000000000004
    x4: 0x000000010200cd00   x5: 0x0000000000000000   x6: 0x000000010190c770   x7: 0x0000000000000000
    x8: 0x1fd53e322d590021   x9: 0x1fd53e322d590021  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000001  x13: 0x0000000000000002  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x00000001d83aa720  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000020
   x20: 0x000000016f423b20  x21: 0x0000000000000020  x22: 0x000000010200cca0  x23: 0x000000010280b480
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016f423cd8   fp: 0x000000016f423ae0   lr: 0x0000000100b1b97c
    sp: 0x000000016f423ad0   pc: 0x00000001d83aa724 cpsr: 0x60000000
   esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
0x1009dc000 - 0x10106bfff frida-server arm64  <eed454bbb67d392d90dc9a4a58fed889> /usr/sbin/frida-server
0x101164000 - 0x10116ffff libobjc-trampolines.dylib arm64  <b8c2db0f13bb343d93d8e8c6f6cee07e> /usr/lib/libobjc-trampolines.dylib
0x101178000 - 0x10118ffff libsubstitute.dylib arm64  <0fbb851edb86325daa9a49f1a1722445> /usr/lib/libsubstitute.dylib
0x1011a0000 - 0x1011a7fff libsubstrate.dylib arm64  <52123f7ce68a36dc8d3f93dca9c4dad6> /usr/lib/libsubstrate.dylib
0x10130c000 - 0x101377fff dyld arm64  <f756a8d55a803b4d996236fe0e7638c2> /usr/lib/dyld
0x1013f8000 - 0x1017e7fff substitute-inserter.dylib arm64  <9ee31a91880e3d089c9d10a394ff8b48> /usr/lib/substitute-inserter.dylib
0x101a00000 - 0x101cbffff substitute-loader.dylib arm64  <17f0fb61e3eb3a7cb2fe6e82d6769b0c> /usr/lib/substitute-loader.dylib
0x192593000 - 0x192611fff libdispatch.dylib arm64  <6c143c51288f3cd084dd17b9a0aaee62> /usr/lib/system/libdispatch.dylib
0x192612000 - 0x192648fff libdyld.dylib arm64  <e31c0887c99930479b80203248ec2396> /usr/lib/system/libdyld.dylib
0x192649000 - 0x1928a0fff libicucore.A.dylib arm64  <9fc7dac3deed3a479abbe36867045ba5> /usr/lib/libicucore.A.dylib
0x1928a1000 - 0x192c4afff CoreFoundation arm64  <96f8386dd88a3c89a323a17975c3317f> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x192e2e000 - 0x192ea6fff SystemConfiguration arm64  <75fec68015053f2e84dc4a0a8586c617> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x192f92000 - 0x193413fff CFNetwork arm64  <e261fa7130e23e6a8db232ecf79b30bf> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x193414000 - 0x193ad9fff libnetwork.dylib arm64  <c67a2d7144153f82939965c3956520ae> /usr/lib/libnetwork.dylib
0x193b4b000 - 0x193de5fff Foundation arm64  <f1bc26a1f5bb36f7a65ad5f232dbf902> /System/Library/Frameworks/Foundation.framework/Foundation
0x199932000 - 0x199a6ffff Security arm64  <149f8d12822a31a198bf48ce690f678d> /System/Library/Frameworks/Security.framework/Security
0x19b5ce000 - 0x19b5f3fff libsystem_info.dylib arm64  <3536d46d36cd3af4b92c67e4bdebd8c6> /usr/lib/system/libsystem_info.dylib
0x19b5f4000 - 0x19b670fff libsystem_c.dylib arm64  <edf3e843a62a3dd092ccebe94d5a83e3> /usr/lib/system/libsystem_c.dylib
0x19cf52000 - 0x19cff8fff IOKit arm64  <c50846c1e80d37e886984cf410de47a6> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x1a0efd000 - 0x1a0f5afff libMobileGestalt.dylib arm64  <448540b0eca03930b98b2d18101114d6> /usr/lib/libMobileGestalt.dylib
0x1a13ca000 - 0x1a13ecfff libsystem_malloc.dylib arm64  <9f2d3d4683d9358f972c1cf61c073a31> /usr/lib/system/libsystem_malloc.dylib
0x1a3357000 - 0x1a3366fff libsystem_networkextension.dylib arm64  <0e55773557ba3611994ce782f3cbfe75> /usr/lib/system/libsystem_networkextension.dylib
0x1a6366000 - 0x1a639bfff libobjc.A.dylib arm64  <7cad222912fa3d6c82005306fb157fa4> /usr/lib/libobjc.A.dylib
0x1a63fc000 - 0x1a6455fff libc++.1.dylib arm64  <88496d66c6683f1797c5d0c91e8bee42> /usr/lib/libc++.1.dylib
0x1a6456000 - 0x1a646efff libc++abi.dylib arm64  <464199d1cdfe3663bedfcbc1b5f19491> /usr/lib/libc++abi.dylib
0x1a65d9000 - 0x1a6619fff CoreAutoLayout arm64  <83a9b00eb095347aa9a2fd147deb1d75> /System/Library/PrivateFrameworks/CoreAutoLayout.framework/CoreAutoLayout
0x1a7fb4000 - 0x1a7fcafff libsystem_trace.dylib arm64  <4ed5b6b480e9322784b590bc92570931> /usr/lib/system/libsystem_trace.dylib
0x1aaf4b000 - 0x1ab0cdfff libsqlite3.dylib arm64  <a814e2dc328e3acd860ff0e3ee3a180e> /usr/lib/libsqlite3.dylib
0x1abc61000 - 0x1abc6bfff libsystem_notify.dylib arm64  <4dbd2e3e6bc43d1388d0e01ba0cc4e07> /usr/lib/system/libsystem_notify.dylib
0x1abd16000 - 0x1abd85fff libcorecrypto.dylib arm64  <071f7a201cf6324783d7d4e309a64c16> /usr/lib/system/libcorecrypto.dylib
0x1abe79000 - 0x1abe8ffff libsystem_asl.dylib arm64  <441adb81097f31d6a85d380a72993d66> /usr/lib/system/libsystem_asl.dylib
0x1af5a5000 - 0x1af5affff IOMobileFramebuffer arm64  <674f742e890231f3b8999fac2c9eb8fa> /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
0x1b20ae000 - 0x1b20bffff IOSurface arm64  <19dd2ad445e03197a5c453b357f361a0> /System/Library/Frameworks/IOSurface.framework/IOSurface
0x1b264e000 - 0x1b2655fff libsystem_symptoms.dylib arm64  <cf41ba3e1ea634e58692d79f7c1b90b8> /usr/lib/system/libsystem_symptoms.dylib
0x1bd336000 - 0x1bd366fff libsystem_kernel.dylib arm64  <8bcb6ff951623657a2e25ce5704353e6> /usr/lib/system/libsystem_kernel.dylib
0x1bfdac000 - 0x1bfdadfff libSystem.B.dylib arm64  <5f81896adca13ef7999f6c5da89a750b> /usr/lib/libSystem.B.dylib
0x1c01ee000 - 0x1c025cfff libarchive.2.dylib arm64  <cfb67f017e673b5294fabf9e2d00cc61> /usr/lib/libarchive.2.dylib
0x1d03d3000 - 0x1d03d3fff SoftLinking arm64  <2a4d987221d13057a2e4287595be79b5> /System/Library/PrivateFrameworks/SoftLinking.framework/SoftLinking
0x1d6c90000 - 0x1d6cc2fff libCRFSuite.dylib arm64  <a30268c7824a34c59182cf051f933a2c> /usr/lib/libCRFSuite.dylib
0x1d7376000 - 0x1d738cfff libapple_nghttp2.dylib arm64  <741cbe1e00f93a20b845d77885621920> /usr/lib/libapple_nghttp2.dylib
0x1d74ae000 - 0x1d74befff libbsm.0.dylib arm64  <62262c68bf203584b2ea3889b8647e16> /usr/lib/libbsm.0.dylib
0x1d74bf000 - 0x1d74cbfff libbz2.1.0.dylib arm64  <bdcdbdcc24953c7e90401c44963079e0> /usr/lib/libbz2.1.0.dylib
0x1d74cc000 - 0x1d74ccfff libcharset.1.dylib arm64  <72b0c36f725f38fea3579a515aaf64b9> /usr/lib/libcharset.1.dylib
0x1d74df000 - 0x1d74f6fff libcompression.dylib arm64  <36dd56ca87a33b8bbc2e9ee086e82284> /usr/lib/libcompression.dylib
0x1d74f7000 - 0x1d750cfff libcoretls.dylib arm64  <31987a4e4ec23c89952efad70a0d71d5> /usr/lib/libcoretls.dylib
0x1d750d000 - 0x1d750efff libcoretls_cfhelpers.dylib arm64  <56fa9fe8ebb83d17872877e4c5cd0848> /usr/lib/libcoretls_cfhelpers.dylib
0x1d7539000 - 0x1d7540fff libdns_services.dylib arm64  <8d3832488b4333b492251a634982e109> /usr/lib/libdns_services.dylib
0x1d755e000 - 0x1d755efff libenergytrace.dylib arm64  <ee2039679a7d332c8ac386c6ddd87e24> /usr/lib/libenergytrace.dylib
0x1d75ae000 - 0x1d769ffff libiconv.2.dylib arm64  <6bf1c6e1e4b93cc3928eaa07c4ecdfc5> /usr/lib/libiconv.2.dylib
0x1d76bd000 - 0x1d76befff liblangid.dylib arm64  <982686583ed13ebaa2cc14345035abe9> /usr/lib/liblangid.dylib
0x1d76cb000 - 0x1d76e3fff liblzma.5.dylib arm64  <60e6e4ad8b823583b81e7e39df26637f> /usr/lib/liblzma.5.dylib
0x1d7d57000 - 0x1d7d8afff libpcap.A.dylib arm64  <0d7a2422cdb838ce9604933d6ced3742> /usr/lib/libpcap.A.dylib
0x1d7e81000 - 0x1d7e98fff libresolv.9.dylib arm64  <d007e203385a3a9fad4c45aa4ebc975f> /usr/lib/libresolv.9.dylib
0x1d7ee7000 - 0x1d7fccfff libxml2.2.dylib arm64  <3102a95fbfd13d2292ed7d4f31ce994f> /usr/lib/libxml2.2.dylib
0x1d7ffa000 - 0x1d800bfff libz.1.dylib arm64  <d73106766fb234ab89d92a7d3e5a53e2> /usr/lib/libz.1.dylib
0x1d8238000 - 0x1d823dfff libcache.dylib arm64  <93f46de334c83b548e87b685e63149e7> /usr/lib/system/libcache.dylib
0x1d823e000 - 0x1d824afff libcommonCrypto.dylib arm64  <163c756fa4413bb7b2ca067463d98526> /usr/lib/system/libcommonCrypto.dylib
0x1d824b000 - 0x1d824ffff libcompiler_rt.dylib arm64  <6749df438089311b939a87f9ca479efd> /usr/lib/system/libcompiler_rt.dylib
0x1d8250000 - 0x1d8258fff libcopyfile.dylib arm64  <5ea5d77aebc930459a3ccf1838e73c6b> /usr/lib/system/libcopyfile.dylib
0x1d8336000 - 0x1d8336fff liblaunch.dylib arm64  <a0b8f064a9ee310e8b976e27f49a05f2> /usr/lib/system/liblaunch.dylib
0x1d8337000 - 0x1d833cfff libmacho.dylib arm64  <863174fc64663104aca38d1d4a82d075> /usr/lib/system/libmacho.dylib
0x1d833d000 - 0x1d833ffff libremovefile.dylib arm64  <fc34eec2b9013ebbbc31e73f38842b70> /usr/lib/system/libremovefile.dylib
0x1d8340000 - 0x1d8341fff libsystem_blocks.dylib arm64  <bc8afa7d401e35f789e89e7a59aef82b> /usr/lib/system/libsystem_blocks.dylib
0x1d8342000 - 0x1d8344fff libsystem_collections.dylib arm64  <828126f3e6583da2aceac728678588de> /usr/lib/system/libsystem_collections.dylib
0x1d8345000 - 0x1d8349fff libsystem_configuration.dylib arm64  <27db1d5d607530bf888edca2c13e80ef> /usr/lib/system/libsystem_configuration.dylib
0x1d834a000 - 0x1d835cfff libsystem_containermanager.dylib arm64  <cb5192ce591f3bb8bc455646bb298477> /usr/lib/system/libsystem_containermanager.dylib
0x1d835d000 - 0x1d835efff libsystem_coreservices.dylib arm64  <b3a52ad613a83868ab485b08b9c8fa23> /usr/lib/system/libsystem_coreservices.dylib
0x1d835f000 - 0x1d8368fff libsystem_darwin.dylib arm64  <e5bec594b4643527b60ef752cb6e3386> /usr/lib/system/libsystem_darwin.dylib
0x1d8369000 - 0x1d8371fff libsystem_dnssd.dylib arm64  <e4268fdd91b5313994546631865c32ca> /usr/lib/system/libsystem_dnssd.dylib
0x1d8372000 - 0x1d8374fff libsystem_featureflags.dylib arm64  <1e7cd17eb5283b85bf4a27e1aa8dfa3e> /usr/lib/system/libsystem_featureflags.dylib
0x1d8375000 - 0x1d83a2fff libsystem_m.dylib arm64  <dedeec341f9e3964a5ff79cddc6a811e> /usr/lib/system/libsystem_m.dylib
0x1d83a3000 - 0x1d83adfff libsystem_platform.dylib arm64  <abb790d318753996aaee06e7568ea1c9> /usr/lib/system/libsystem_platform.dylib
0x1d83ae000 - 0x1d83aefff libsystem_product_info_filter.dylib arm64  <61b5d8563fb33fe9b30540a45f659732> /usr/lib/system/libsystem_product_info_filter.dylib
0x1d83af000 - 0x1d83bffff libsystem_pthread.dylib arm64  <93c7f0dc89f13162a1196fc88028d027> /usr/lib/system/libsystem_pthread.dylib
0x1d83c0000 - 0x1d83c3fff libsystem_sandbox.dylib arm64  <176b1087aaad36258e7ffc497673706c> /usr/lib/system/libsystem_sandbox.dylib
0x1d83c4000 - 0x1d83cdfff libunwind.dylib arm64  <b7cd41ad513335ac84299bc0dcc6511b> /usr/lib/system/libunwind.dylib
0x1d83ce000 - 0x1d8400fff libxpc.dylib arm64  <e3552d23adfb36feb7d0b23090553c49> /usr/lib/system/libxpc.dylib

EOF
```

**Comment by frifox** [comment]
Getting same error on iPhone 6 running latest supported iOS 12.5.7:

```
iPhone:~ root# frida-server --version
17.2.6

iPhone:~ root# uname -a
Darwin iPhone 18.7.0 Darwin Kernel Version 18.7.0: Mon Nov  9 15:07:15 PST 2020; root:xnu-4903.272.3~3/RELEASE_ARM64_T7000 iPhone7,2 arm64 N61AP Darwin

iPhone:~ root# frida-server
Segmentation fault: 11
```

```
cat /var/mobile/Library/Logs/CrashReporter/frida-server-2025-07-01-140516.ips

{"app_name":"frida-server","app_version":"","bug_type":"109","timestamp":"2025-07-01 14:05:16.47 -0700","os_version":"iPhone OS 12.5.2 (16H30)","incident_id":"19B6C4E0-0553-4FA0-B7BE-72611A61D3AA","slice_uuid":"4c89fafc-0a56-35f1-b89f-f7ebc0c7e0c8","build_version":"","is_first_party":true,"share_with_app_devs":false,"name":"frida-server"}
Incident Identifier: 19B6C4E0-0553-4FA0-B7BE-72611A61D3AA
CrashReporter Key:   3df4b12a4d0c082573760d32fa11269c02f86caa
Hardware Model:      iPhone7,2
Process:             frida-server [1507]
Path:                /usr/sbin/frida-server
Identifier:          frida-server
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           re.frida.server [121]


Date/Time:           2025-07-01 14:05:16.4153 -0700
Launch Time:         2025-07-01 14:05:16.3259 -0700
OS Version:          iPhone OS 12.5.2 (16H30)
Baseband Version:    7.80.04
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4308746240
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->
      __TEXT                 0000000100d24000-00000001013b4000 [ 6720K] r-x/r-x SM=COW  .../frida-server

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [1507]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_c.dylib             	0x0000000206b5a17c 0x206b01000 + 364924
1   frida-server                  	0x0000000100d86e54 0x100d24000 + 405076
2   frida-server                  	0x0000000100d86c74 0x100d24000 + 404596
3   frida-server                  	0x0000000100d86b30 0x100d24000 + 404272
4   frida-server                  	0x0000000100d80b28 0x100d24000 + 379688
5   frida-server                  	0x0000000100d8028c 0x100d24000 + 377484
6   frida-server                  	0x0000000100d2836c 0x100d24000 + 17260
7   libdyld.dylib                 	0x0000000206ab68e0 0x206ab5000 + 6368

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x000000000000002f   x2: 0x000000016f0db9ec   x3: 0x0000000000000004
    x4: 0x000000012800fd00   x5: 0x0000000000000000   x6: 0xfffffffffffffffc   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x000000000000002f  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000001  x13: 0x0000000000000002  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000206b5a16c  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x00000001280059f0
   x20: 0x000000016f0dbbd0  x21: 0x0000000000000000  x22: 0x000000012800fc80  x23: 0x0000000128805880
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x000000016f0dbd80   fp: 0x000000016f0dbbc0   lr: 0x0000000100d86e54
    sp: 0x000000016f0dbba0   pc: 0x0000000206b5a17c cpsr: 0x60000000

Binary Images:
0x100d24000 - 0x1013b3fff frida-server arm64  <4c89fafc0a5635f1b89ff7ebc0c7e0c8> /usr/sbin/frida-server
0x1016c4000 - 0x10171bfff dyld arm64  <c08f675c016c30b8a87de35aef8f6b20> /usr/lib/dyld
0x2061cf000 - 0x2061d0fff libSystem.B.dylib arm64  <10b5facbbd7533a4b9951f11d9fe8a24> /usr/lib/libSystem.B.dylib
0x2061d1000 - 0x206226fff libc++.1.dylib arm64  <b3777a85ba99325c84a094403210292c> /usr/lib/libc++.1.dylib
0x206227000 - 0x206239fff libc++abi.dylib arm64  <5fa69db3be2b326a960e679cbc20cdd2> /usr/lib/libc++abi.dylib
0x20623a000 - 0x2069c1fff libobjc.A.dylib arm64  <eb1d41ef606536f381963e12707039bd> /usr/lib/libobjc.A.dylib
0x2069c2000 - 0x2069c6fff libcache.dylib arm64  <c8e0816ff45939579ffa7d543ebef602> /usr/lib/system/libcache.dylib
0x2069c7000 - 0x2069d2fff libcommonCrypto.dylib arm64  <0c58b1e3fed53c33b9c3af8c0b9688f9> /usr/lib/system/libcommonCrypto.dylib
0x2069d3000 - 0x2069d7fff libcompiler_rt.dylib arm64  <a442acb44c1830739d1f4078a6598055> /usr/lib/system/libcompiler_rt.dylib
0x2069d8000 - 0x2069e0fff libcopyfile.dylib arm64  <f0cfa6e3e0c83b8a827f4b7102b78503> /usr/lib/system/libcopyfile.dylib
0x2069e1000 - 0x206a44fff libcorecrypto.dylib arm64  <fa5e08a391303ba8b41ff656299b1238> /usr/lib/system/libcorecrypto.dylib
0x206a45000 - 0x206ab4fff libdispatch.dylib arm64  <c96b693c750f359ca48e164a4d4b6dc5> /usr/lib/system/libdispatch.dylib
0x206ab5000 - 0x206adefff libdyld.dylib arm64  <a9559a6839e23e5791cf11fad43eb80a> /usr/lib/system/libdyld.dylib
0x206adf000 - 0x206adffff liblaunch.dylib arm64  <9e2f4992c6473276807823b419a8f3a2> /usr/lib/system/liblaunch.dylib
0x206ae0000 - 0x206ae5fff libmacho.dylib arm64  <41daeba77c823cbbb7433df85dedbea4> /usr/lib/system/libmacho.dylib
0x206ae6000 - 0x206ae7fff libremovefile.dylib arm64  <ec0eac76535531809974293637f8a0b8> /usr/lib/system/libremovefile.dylib
0x206ae8000 - 0x206afffff libsystem_asl.dylib arm64  <c292e3c7f29c3a619115f8a0b4a57d48> /usr/lib/system/libsystem_asl.dylib
0x206b00000 - 0x206b00fff libsystem_blocks.dylib arm64  <833e4ea3a9d83ad7afcfc45e6ee1bc99> /usr/lib/system/libsystem_blocks.dylib
0x206b01000 - 0x206b82fff libsystem_c.dylib arm64  <7b832a1730893fcf9055cf7063826182> /usr/lib/system/libsystem_c.dylib
0x206b83000 - 0x206b87fff libsystem_configuration.dylib arm64  <13a2e054287e30e887beeeb1a3e50eb1> /usr/lib/system/libsystem_configuration.dylib
0x206b88000 - 0x206b8ffff libsystem_containermanager.dylib arm64  <06f0fa92ff9d3eb6812b21cef1296d45> /usr/lib/system/libsystem_containermanager.dylib
0x206b90000 - 0x206b91fff libsystem_coreservices.dylib arm64  <135bee020972348ca4a4ff2df261aa28> /usr/lib/system/libsystem_coreservices.dylib
0x206b92000 - 0x206b98fff libsystem_darwin.dylib arm64  <379f49c976333543ad6bcbbcd4eeb975> /usr/lib/system/libsystem_darwin.dylib
0x206b99000 - 0x206b9ffff libsystem_dnssd.dylib arm64  <c8bc4950915933d5b9e09115a677e37c> /usr/lib/system/libsystem_dnssd.dylib
0x206ba0000 - 0x206bdffff libsystem_info.dylib arm64  <a0a1a97187b53086bd4234adc39ceeb7> /usr/lib/system/libsystem_info.dylib
0x206be0000 - 0x206c0afff libsystem_kernel.dylib arm64  <a16449a0af83376293a61f061816b817> /usr/lib/system/libsystem_kernel.dylib
0x206c0b000 - 0x206c38fff libsystem_m.dylib arm64  <fa9516fd3ba932878aa5d790a1de4e91> /usr/lib/system/libsystem_m.dylib
0x206c39000 - 0x206c5bfff libsystem_malloc.dylib arm64  <9a11b06b2b0b3003860a0071ee67c3d0> /usr/lib/system/libsystem_malloc.dylib
0x206c5c000 - 0x206c67fff libsystem_networkextension.dylib arm64  <219380cbf26d348587c46347b3f993be> /usr/lib/system/libsystem_networkextension.dylib
0x206c68000 - 0x206c6efff libsystem_notify.dylib arm64  <a71accc7cd90388895048ee985825adc> /usr/lib/system/libsystem_notify.dylib
0x206c6f000 - 0x206c79fff libsystem_platform.dylib arm64  <463a90f819f832e28da7dbbdb9cb3ef3> /usr/lib/system/libsystem_platform.dylib
0x206c7a000 - 0x206c8afff libsystem_pthread.dylib arm64  <9e64505eb2233f998d25a7ef27684fcf> /usr/lib/system/libsystem_pthread.dylib
0x206c8b000 - 0x206c8dfff libsystem_sandbox.dylib arm64  <fa1d42ebbde23587a198833a1294e8e1> /usr/lib/system/libsystem_sandbox.dylib
0x206c8e000 - 0x206c95fff libsystem_symptoms.dylib arm64  <2ba35b43355736baba119e83f6162657> /usr/lib/system/libsystem_symptoms.dylib
0x206c96000 - 0x206cabfff libsystem_trace.dylib arm64  <4320113258db3d2d9781206282c2e848> /usr/lib/system/libsystem_trace.dylib
0x206cac000 - 0x206cb1fff libunwind.dylib arm64  <d27ff8546a3b32d2af44a1cd0e499c93> /usr/lib/system/libunwind.dylib
0x206cb2000 - 0x206cdffff libxpc.dylib arm64  <b2072bab23da3d9895611d854a2b9db9> /usr/lib/system/libxpc.dylib
0x206ce0000 - 0x206f3bfff libicucore.A.dylib arm64  <9cb75b8216a7321a9bfd6f9133337cc3> /usr/lib/libicucore.A.dylib
0x206f3c000 - 0x206f4dfff libz.1.dylib arm64  <6dc41c4168cb3a21b450862472c6ff37> /usr/lib/libz.1.dylib
0x206f4e000 - 0x2072acfff CoreFoundation arm64  <476ba5dd461231ec9dae8901e3b92d43> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x2072ad000 - 0x2072bdfff libbsm.0.dylib arm64  <7b3b671039803a11b038ccdb29038709> /usr/lib/libbsm.0.dylib
0x2072be000 - 0x2072befff libenergytrace.dylib arm64  <c63f5e28b675362b90251757c0cfda14> /usr/lib/libenergytrace.dylib
0x2072bf000 - 0x20734dfff IOKit arm64  <e233ec7599893896b1950213c4b46b21> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x20734e000 - 0x207435fff libxml2.2.dylib arm64  <4c96acf5be5439799d591e40f73526b3> /usr/lib/libxml2.2.dylib
0x207436000 - 0x207443fff libbz2.1.0.dylib arm64  <35c4fd3b0b1532309e293e47c6a5bd18> /usr/lib/libbz2.1.0.dylib
0x207444000 - 0x20745cfff liblzma.5.dylib arm64  <ee07aa8b83b73fada37ecc7dc1bc4ff9> /usr/lib/liblzma.5.dylib
0x20745d000 - 0x2075d6fff libsqlite3.dylib arm64  <477c0ff57e703d93abb26d15844b4be0> /usr/lib/libsqlite3.dylib
0x2075d7000 - 0x20760bfff libMobileGestalt.dylib arm64  <b312693e780230c5801c976566a28e15> /usr/lib/libMobileGestalt.dylib
0x20760c000 - 0x2079b9fff CFNetwork arm64  <faf50cd8542e3398ab432ab6237e8857> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x2079ba000 - 0x207ca4fff Foundation arm64  <4cea07d90b363457b6f537300db76dc2> /System/Library/Frameworks/Foundation.framework/Foundation
0x207ca5000 - 0x207db3fff Security arm64  <8c632b99bcfd3650a1de096be8b404ab> /System/Library/Frameworks/Security.framework/Security
0x207db4000 - 0x207e1dfff SystemConfiguration arm64  <03c18281b3af39528270f52e3d57818c> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x207e1e000 - 0x207e50fff libCRFSuite.dylib arm64  <8299a6467af837ffbe05ddc263b650c3> /usr/lib/libCRFSuite.dylib
0x207e51000 - 0x207e67fff libapple_nghttp2.dylib arm64  <768786825cbb31f387cddc8c340f3a62> /usr/lib/libapple_nghttp2.dylib
0x207e68000 - 0x207e91fff libarchive.2.dylib arm64  <c914f1c95a1a30f9bd36597e16a51b53> /usr/lib/libarchive.2.dylib
0x207f5a000 - 0x207f70fff libcoretls.dylib arm64  <99dd96d8696b32e6bdea3cb304e08854> /usr/lib/libcoretls.dylib
0x207f71000 - 0x207f72fff libcoretls_cfhelpers.dylib arm64  <eb0f2360e81f3b799eb6a118c03e18d3> /usr/lib/libcoretls_cfhelpers.dylib
0x207f73000 - 0x207f74fff liblangid.dylib arm64  <60639c92a94733cfb3d6d1dcfcf03b55> /usr/lib/liblangid.dylib
0x207f75000 - 0x2082e5fff libnetwork.dylib arm64  <30bf4104f3603f0e8d419b576d5d96f1> /usr/lib/libnetwork.dylib
0x2082e6000 - 0x208319fff libpcap.A.dylib arm64  <968ceb0dd0db314cb5740c81546f55a5> /usr/lib/libpcap.A.dylib
0x211b9c000 - 0x211bb4fff libresolv.9.dylib arm64  <f479bf5f7c84369f85ec2cf036d053b2> /usr/lib/libresolv.9.dylib

EOF
```

**Comment by NightWuYo** [comment]
Same issue here, with iPad 7th generation.

frida_16.6.6_iphoneos-arm.deb works well, but got "segmentation fault" with version 17.2.16

root# uname -a
Darwin iPadAir 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct  9 22:41:51 PDT 2019; root:xnu-6153.42.1~1/RELEASE_ARM64_T8010 iPad7,11 arm Darwin
