### ISSUE TITLE
device.spawn causes device to freeze/reboot (iOS Frida 32-bit)

### ISSUE THREAD

**Issue by nssecur1ty** [frida/frida#373]
Using version 10.6.21 of Frida 32 bit (from the official frida cydia repo) and frida (python) and 10.6.21 on macOS Sierra 10.12.6 using device.spawn(['bundle.id']) always either causes the device to freeze up (iPhone 4s iOS 8.2.1 jailbroken with evasion) or reboot (iPad 2 iOS 9.3.5 jailbroken with Phoenix)

output (4s iOS 8.2.1):

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mt/frida/frida/classWatch.py", line 34, in <module>
    pid = device.spawn(['com.apple.mobilemail'])
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.NotSupportedError: unable to launch iOS app: timeout
```

output (iPad 2 iOS  9.3.5):

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mt/frida/frida/classWatch.py", line 34, in <module>
    pid = device.spawn(['com.apple.mobilemail'])
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.TransportError: the connection is closed
```

**Comment by nssecur1ty** [comment]
Using a workaround for now ... http://sultan.readthedocs.io/en/latest/ + https://github.com/bored-engineer/iOS-sbutils (sblaunch). Worked for me on both iOS 8.2.1 and 9.3.5 (iPhone 4s)

**Comment by snooze6** [comment]
Same problem here, I can confirm this issue.

**Comment by oleavr** [comment]
Should be fixed in the latest version (10.6.40).

**Comment by Qsec** [comment]
Still experiencing this issue - iPod touch 5th gen, iOS 9.3.5, jailbroken using phoenix.
Python script causes iPod to reboot on device.spawn. Output:

`...
  File "/usr/local/lib/python3.4/dist-packages/frida/core.py", line 85, in spawn
    return self._impl.spawn(argv)
frida.TransportError: the connection is closed
`

Using Frida for 32-bit devices, (10.6.40), from cydia repo

**Comment by oleavr** [comment]
Afraid this won't ever be fixed unless somebody volunteers their time to investigate it. (I don't have any 32-bit devices to test on.)

**Comment by masbog** [comment]
@nssecur1ty and @oleavr i was used like this :

> $ frida -U -f com.masbog.isJB-ObjC

i don't know it must be %resume in terminal after "Spawned", if not will be terminate in seconds

> [iPhone::com.masbog.isJB-ObjC]-> Process terminated

maybe this same issues on FiOS, why after spawned the application was terminated on device...

**Comment by 0xra** [comment]
with iPod touch iOS 9.3.5 jailbroken using phoenix seems that the app looses it's entitlements once frida injects it's agent into the process. this happens when using simple frida -U APPNAME without -f flag

getting this from /private/var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/security.log.20180417T134009Z
`Apr 17 14:57:30 securityd[85] <Notice> [engine{} ]: engine  (null): will-commit api 1 changes
Apr 17 14:57:33 securityd[85] <Notice> [item{} ]: item SecDbItemDoInsert inserted O,genp,E9733F4A,L,dku,com.apple.apsd,426,acct,svce,v_Data,musr,20180417135733.261669Z,F2F6669A
Apr 17 14:57:33 securityd[85] <Notice> [engine{} ]: engine  (null): will-commit api 1 changes
Apr 17 14:57:46 securityd[85] <Error> [SecLogging{} ]:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Apr 17 14:57:46 securityd[85] <Error> [SecLogging{} ]:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Apr 17 14:57:46 securityd[85] <Error> [SecLogging{} ]:  SecOCSPSingleResponseCreate OCSPResponse: single response has extension(s).
Apr 17 14:58:36 securityd[85] <Notice> [item{} ]: item SecDbItemDoInsert inserted O,genp,038438AE,L,ak,SGGM6D27TK.com.microsoft.azureauthenticator,427,acct,svce,v_Data,musr,20180417135836.986502Z,5702E190
Apr 17 14:58:36 securityd[85] <Notice> [engine{} ]: engine  (null): will-commit api 1 changes
Apr 17 14:59:22 securityd[85] <Notice> [user{} ]: SecTaskLoadEntitlements failed error=22 cs_flags=e00500e, task->pid_self=-1
Apr 17 14:59:22 securityd[85] <Notice> [user{} ]: SecTaskCopyDebugDescription: Microsoft Authen[480]
Apr 17 14:59:22 securityd[85] <Error> [SecLogging{} ]:  secTaskDiagnoseEntitlements MISSING keychain entitlements: raw entitlement values: <CFBasicHash 0x17e43250 [0x38a62170]>{type = mutable dict, count = 0,
        entries =>
        }
Apr 17 14:59:22 securityd[85] <Error> [SecLogging{} ]:  secTaskDiagnoseEntitlements MISSING keychain entitlements: original ag: (null)
Apr 17 14:59:22 securityd[85] <Error> [SecLogging{} ]:  secTaskDiagnoseEntitlements MISSING keychain entitlements: newly parsed ag: (null)
Apr 17 14:59:22 securityd[85] <Error> [SecLogging{} ]:  __security_simulatecrash Simulating crash, reason: keychain entitlement(s) missing, code=53c00007
Apr 17 14:59:23 securityd[85] <Error> [SecLogging{} ]:  securityd_xpc_dictionary_handler Microsoft Authen[480] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
Apr 17 14:59:23 securityd[85] <Notice> [user{} ]: SecTaskLoadEntitlements failed error=22 cs_flags=e00500e, task->pid_self=-1`


i assume this is why launchd crashes 

frida version 8.2.5 does work with -f flag, versions 8.1.14 and 9.0.13 do not work with phoenix on ios 9.3.5 32-bit

any ideas what i could be?
