### ISSUE TITLE
FridaGadget.dylib' does not contain bitcode

### ISSUE THREAD

**Issue by 0x00-0xFF** [frida/frida#84]
After importing the dylib I cannot install the project (using xcode 7.1):
FridaGadget.dylib' does not contain bitcode

ld: '/Users/anonymous/Documents/PROGRAMMING/ios/xcode/helloworld/Frameworks/FridaGadget.dylib' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by oleavr** [comment]
Thanks! Will fix this soon.

**Comment by oleavr** [comment]
Fixed, just re-download FridaGadget.dylib and the new version should work.

**Comment by 0x00-0xFF** [comment]
Still doesn't work...
Without bitcode enabled:
Frida: frida-gum/gum/backend-darwin/gumcodesegment-darwin.c:212:gum_code_segment_realize: assertion failed: (res == 0)
With bitcode enabled: 
FridaGadget.dylib' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jacobrosenthal** [comment]
Im getting this as well with xcode 7.2.1

**Comment by 0x00-0xFF** [comment]
This problem still occurs. Any news/update?

**Comment by ay-kay** [comment]
Still (or again) seems to be an issue with latest FridaGadget.dylib (9.0.5)?
